Add traffic lights
C-Naydenov18214/Traffic-Simulation pull request #4
Opened 2021-04-27 12:26 UTC by Jlemix

2021-04-27 18:29 UTC, SpykeX3 requested changes

2021-04-27 18:29 UTC, SpykeX3 commented on Engine/src/main/java/ru/nsu/team/simulator/MinimalisticNodeProcessing.java
> +        if (trafficLight == null || trafficLight.timeBlocked(road, time) == 0) {
Каждая машина живет в своем времени, если посмотреть выше, где пишется в плейбек, то можно увидеть, что текущее время у машины можно посчитать как `time + timeInterval - car.getTimeLeft()`

2021-04-27 18:29 UTC, SpykeX3 commented on Engine/src/main/java/ru/nsu/team/simulator/MinimalisticNodeProcessing.java
>          car.setSpeed(0);
Если на светофоре горит красный, то машина должна ждать зеленый свет (скорость уменьшается до нуля, а ее оставшееся время уменьшается на время ожидания зеленого света)

2021-04-27 18:29 UTC, SpykeX3 commented on Engine/src/test/java/ru/nsu/team/simulator/SimulatorTest.java
> +        trafficLight.addConfig(config1);
Если светофоры всегда горят зеленым, то тест не отличается от существующего простого теста на способность запускаться. Чтобы светофор имел разные состояния у него должно быть несколько конфигов

2021-04-27 18:29 UTC, SpykeX3 commented on Engine/src/test/java/ru/nsu/team/simulator/SimulatorTest.java
> +        RoadMap rm = createSampleLineRoadMapTL();
Здесь лучше создать новый тест

2021-05-03 06:37 UTC, Jlemix commented on Engine/src/test/java/ru/nsu/team/simulator/SimulatorTest.java
> +        trafficLight.addConfig(config1);
может я что-то не понял, но вроде как раз здесь и добавляется пара конфигов одному светофору)

2021-05-19 05:47 UTC, SpykeX3 requested changes

2021-05-19 05:47 UTC, SpykeX3 commented on Engine/src/test/java/ru/nsu/team/simulator/SimulatorTest.java
> +        trafficLight.addConfig(config1);
Да, это я криво прочитал

2021-05-19 05:47 UTC, SpykeX3 commented on Engine/src/test/java/ru/nsu/team/simulator/SimulatorTest.java
> +        RoadMap rm = createSampleLineRoadMapTL();
Давай сделаем перекресток и два пересекающихся потока машин, тогда можно будет сделать три теста, где одна дорога всегда красная, а другая зеленая, где вторая красная, а первая зеленая, и где чередуются, тогда можно будет пустить немного машин туда и проверить, что в 1 случае не доехали машины с 1 дороги, во втором со 2, а в 3 все доехали

2021-05-19 05:47 UTC, SpykeX3 commented on Engine/src/main/java/ru/nsu/team/simulator/MinimalisticNodeProcessing.java
>          car.setSpeed(0);
Уже похоже на правду, но есть еще случай, когда у машины много времени и она успевает подождать зеленый свет и проехать ноду в текущей итерации. Надо чтобы если машина успевает подождать и проехать, то это делалось в этой итерации processCar.
Небольшое пояснение, симуляция нод и дорог происходит по этапам, на каждом этапе строится очередь для следующего этапа, изначально в очереди все дороги, начинается с этапа дорог. Если сейчас этап дорог, то в очередь попадают ноды, в которые уперлись машинки с дорог из очереди. Если этап нод, то попадают в очередь те дороги, в которые из нод в очереди приехали машины

2021-06-18 20:02 UTC, merged