Scoring function
C-Naydenov18214/Traffic-Simulation pull request #6
Opened 2021-05-11 14:18 UTC by SpykeX3

Seemed reasonable to use heatmap builder as it has information about average speeds on each road.
Scoring is average of the ((average speed)/max speed)

2021-05-16 15:05 UTC, Jlemix requested changes

2021-05-16 15:05 UTC, Jlemix commented on Engine/src/main/java/ru/nsu/team/entity/report/HeatmapBuilder.java
>              double avgTime = entry.getValue().avgTime;
Запуская тест testSimulator(), есть вероятность поймать случай, в котором avgTime = 0.0, из-за чего getScore() может вернуть Infinity.

2021-05-19 03:26 UTC, SpykeX3 commented on Engine/src/main/java/ru/nsu/team/entity/report/HeatmapBuilder.java
>              double avgTime = entry.getValue().avgTime;
Спасибо, что заметил! Поправил

2021-05-19 03:47 UTC, Jlemix requested changes

2021-05-19 03:47 UTC, Jlemix commented on Engine/src/main/java/ru/nsu/team/entity/report/HeatmapBuilder.java
> +            throw new RuntimeException("No enter record fount for car " + participant);
"fount" - опечатка

2021-05-19 04:02 UTC, SpykeX3 commented on Engine/src/main/java/ru/nsu/team/entity/report/HeatmapBuilder.java
> +            throw new RuntimeException("No enter record fount for car " + participant);
Пофиксил

2021-05-19 04:07 UTC, merged