Log messages for debug
C-Naydenov18214/Traffic-Simulation pull request #7
Opened 2021-05-11 14:19 UTC by SpykeX3

2021-05-16 14:22 UTC, Jlemix requested changes

2021-05-16 14:22 UTC, Jlemix commented on Engine/src/main/java/ru/nsu/team/entity/spawner/Spawner.java
> +        LOG.debug("Will spawn " + toSpawn + "cars");
С пробелом перед "cars" выглядело бы лучше)

2021-05-16 14:22 UTC, Jlemix commented on Engine/src/main/java/ru/nsu/team/entity/spawner/Spawner.java
> +                LOG.debug("Destination " + destination.getId() + "can't be reached from spawner");
Тоже пробельчика перед "can't" нехватает

2021-05-19 02:26 UTC, SpykeX3 commented on Engine/src/main/java/ru/nsu/team/entity/spawner/Spawner.java
> +        LOG.debug("Will spawn " + toSpawn + "cars");
Поправил

2021-05-19 02:26 UTC, SpykeX3 commented on Engine/src/main/java/ru/nsu/team/entity/spawner/Spawner.java
> +                LOG.debug("Destination " + destination.getId() + "can't be reached from spawner");
Поправил

2021-05-19 03:26 UTC, merged